### PR TITLE
irqbalance: prevent NULL pointer dereference in do_one_cpu()

### PR DESCRIPTION
**Pull request by yeyunfeng-dev**
add_cpu_to_cache_domain() will return NULL if memory allocation failure,
so check the return value before invoking add_cache_domain_to_package().

Signed-off-by: Yunfeng Ye <yeyunfeng@huawei.com>

### CODE REVIEW

**Comment by yeyunfeng-dev** [comment]
I have update the patch as your suggest, thanks.

**Comment by nhorman** [comment]
Ok, thank you, that looks like the approach I was thinking of, but don't you want to extend the rebuild flag to get set for the various oom conditions that might arise throughout the build_object_tree process?  like if calloc fails in add_one_node or if the calloc fails in do_one_cpu directly?

**Comment by yeyunfeng-dev** [comment]
ok, but can I  new commit to add  rebuild flag, becuase I have another pull request:  "move numa.c to cputree.c and refactor some numa codes"? thanks.

**Comment by nhorman** [comment]
No, do it here, I've asked before that you not mix and match pull requests like that

**Comment by yeyunfeng-dev** [comment]
ok, I have update the patch, thanks.

**Pull request merged**
