### PR TITLE
Add IRQBALANCE_BANNED_CPULIST to env file and remove some codes

### PR DESCRIPTION
**Pull request by yeyunfeng-dev**
Add IRQBALANCE_BANNED_CPULIST to env file
Remove IRQBALANCE_BANNED_CPUS environment variable
Remove some unused constant macros in constants.h

### CODE REVIEW

**Comment by nhorman** [comment]
removing IRQBALACE_BANNED_CPUs is going to cause breakage for anyone using that environment variable currently on upgrade.  Shouldn't we introduce a deprecation period first?

**Comment by yeyunfeng-dev** [comment]
From the perspective of functional redundancy, it is enough to leave only one environment variable. However, for the consider of compatibility, it is ok to introduce a deprecation period. Of course, if it is removed directly, I think it is also possible for the user to identify the changes,  and handle them with compatibility. 

If the patch "Remove IRQBALANCE_BANNED_CPUS environment variable" not be merged, the other 2 commits is independent patches. Thanks.

**Comment by nhorman** [comment]
yes, I agree.  We could add a deprecation notice as well.  If you will make the requisite changes, I'll merge it all

**Comment by yeyunfeng-dev** [comment]
ok, the patches have been changed

**Comment by nhorman** [comment]
I'm sorry, when I said deprecation notice, I meant for you to write a message into the system log, so that user would be aware of the deprecation, not just individuals reading the code

**Comment by yeyunfeng-dev** [comment]
I have add a log when the environment variable IRQBALANCE_BANNED_CPUS is configured, thanks.

**Comment by nhorman** [comment]
looks good, thanks!

**Pull request merged**
