### PR TITLE
Add basic github workflow based CI

### PR DESCRIPTION
**Pull request by mikey**
This would catch very basic compile issues on x86.

Signed-off-by: Michael Neuling <mikey@neuling.org>

### CODE REVIEW

**Comment by mikey** [comment]
This would catch issues like we fixed in #180 before they are merged.

**Comment by nhorman** [comment]
Irabalance already has travis configured.  I think you should just expand that to encompass nonx86 builds.  If you can do that, I'll gladly merge it

**Comment by mikey** [comment]
Arrh, I missed that :facepalm: 

Can you get travis to hooked into github to so we can see the results on each PR on github? I think you just login to travis with the irqbalance github account and click a few things :-)

**Comment by nhorman** [comment]
Its already noted in the README (the build/passing tag).  I can try to put it somewhere more prominent), but I dont think arbitrary markdown is allowed outside of the README file

**Comment by mikey** [comment]
If you look at something like https://github.com/antonblanchard/microwatt/pulls you can see each PR has tick/cross against it. That is what I was thinking. You should be able to get Travis to report there. (The github workflow does that automatically).

**Comment by nhorman** [comment]
grr, its apparently a bit more complicated than clicking a few buttons, especially for irqbalance that is owned as part of an orgnization rather than by me personally.  I'll look into it shortly

**Comment by neheb** [comment]
@mikey IMO should use something like setup-alpine which has a lot more architectures.

**Comment by nhorman** [comment]
you're welcome to propose a pr if you like

**Pull request closed without merging**
