### PR TITLE
make the parameter line of getline be freeed correctly

### PR DESCRIPTION
**Pull request by hejingxian123**
1 When getline ERRORNO is ENOMEM, the input line will return null. we can't free line when it's null.
2 This buffer should be freed by the user program even if getline() failed.
3 Threre exists file op with no closing before return.

### CODE REVIEW

**Comment by nhorman** [comment]
Theres a simpler way to do this.  POSIX defines free as allowing the freeing of NULL (reducing to a noop).  As such, instead of checking the value of line for being NULL subsequent to the getline call, just set line = NULL prior to the getline call.  Then you just unconditionally free it in the error case

**Comment by hejingxian123** [comment]
The commit has been simpler.

**Comment by nhorman** [comment]
The setup_banned_cpu changes look good, but the do_one_cpu changes could still be simplified.  See the review I started

**Comment by hejingxian123** [comment]
I can't get your meaning  about do_one_cpu. I has reverted the changes about do_one_cpu. You can accept the changes about setup_banned_cpu firstly. Thanks.

**Comment by nhorman** [comment]
What don't you understand?  I provided you a sample diff.

**Comment by hejingxian123** [comment]
I have made changes abount do_one_cpu more simpier. But  I haven't find your provide diff file, due to   I have no experience in this.  If you have more suggestion, you can describe it in the comment. Thanks very much.

**Comment by nhorman** [comment]
Its literally 4 comments up in this discussion

**Comment by hejingxian123** [comment]
I think my modification is already the simplest way to avoid resource release.  I have seen the above comments  more than one thousand times. You say 'Theres a simpler way to do this. POSIX defines free as allowing the freeing of NULL (reducing to a noop). As such, instead of checking the value of line for being NULL subsequent to the getline call, just set line = NULL prior to the getline call. '. I have already done the same as you say. Do you see my modification again? There is already no problem in my modification.  This time I only add ten lines, and it's better than the exist code in irqbalance.

**Comment by nhorman** [comment]
I don't know how to make it any clearer for you.  If you don't want to take the suggestions I've offered, I'll just take care of it myself.

**Pull request closed without merging**
