### PR TITLE
fix sleep interval when sleep_interval is changed by socket

### PR DESCRIPTION
**Pull request by Pyxisha**
currently, in scan, irqbalance compare sleep_interval's address to decide if sleep_interval is changed, accutually this judgement is always false now.

sign_off_by: Shuang Xia <xiashuang1@huawei.com>

### CODE REVIEW

**Comment by nhorman** [comment]
why are you using last_interval in main?  That shouldn't be needed

**Comment by Pyxisha** [comment]
Yeah, I foo. mislead by the original code.

**Comment by nhorman** [comment]
Have you tested this to ensure that changing the sleep time via the irqbalance ui to ensure that the scan interval updates properly?

**Comment by Pyxisha** [comment]
I add a print here:
gboolean scan(gpointer data __attribute__((unused)))
{
        struct timespec now;
        clock_gettime(CLOCK_MONOTONIC, &now);

        log(TO_CONSOLE, LOG_INFO, "%d\n\n\n-----------------------------------------------------------------------------\n", now.tv_sec);

[debug.txt](https://github.com/Irqbalance/irqbalance/files/3397100/debug.txt)

and from the debug output, We can see the sleep interval change from 10s to 5s.

**Pull request merged**
