### PR TITLE
irqbalance: check the length of optarg

### PR DESCRIPTION
**Pull request by liuchao173**
https://github.com/Irqbalance/irqbalance/issues/228

Signed-off-by: Liu Chao <liuchao173@huawei.com>

### CODE REVIEW

**Comment by nhorman** [comment]
what exactly are you fixing here?  I understand wanting to validate your input prior to using it, but getopt_long already does that.  Note the lopts struct and option_string that is passed to getopt long.  For every case in the switch statement, the corresponding option character and lopt entry is followed by a ':' and a 1 in the has_arg field respectively, indicating the option has a required argument.  In the event a valid argument is not provided getopt_long returns '?', leading us to print usage and exit.  I don't see what this patch is improving

**Comment by liuchao173** [comment]
For example, when use "--banirq=" without any value, optarg is an empty string and val will be 0. It will cause IRQ 0 is banned.
see the issue:
https://github.com/Irqbalance/irqbalance/issues/228

**Comment by nhorman** [comment]
ok, my point remains.  Please look at the function call for getopt_long:
  while ((opt = getopt_long(argc, argv,
                "odfjVi:p:s:c:l:m:t:e:",
                lopts, &longind)) != -1) {

the option string contains the substring "i:", and the banirq line in lopts is:
{"banirq", 1 , NULL, 'i'},
indicating a required argument

if getopt_long is returning 'i' when you provide --banirq= on the command line, getopt_long is the problem.  getopt_long should either be returning '?" in that case, or (in the case its returning 'i') should set optarg to "" (i.e. a non-null string that has no characters in it, a pointer to '\0').  In either case checking for NULL shouldn't be the solution here

**Comment by liuchao173** [comment]
--banirq=, --banirq="", -i ""
"" is also a argument. getopt_long returning 'i' and set optarg to "". I use strlen to check it rather than checking for NULL.
How about checking the value of val and don't ban IRQ0

**Comment by nhorman** [comment]
We're saying the same thing.  If you pass "" as the argent.to -i, and
getopt_long returns 'i', then optarg should be set to a non null pointer to
a string who's first element is '\0'.

That said, using strlen shouldn't be needed there (though it likely
works).  You can probably still use strtoull with the second arg set to
non-null, using that to determine an error in parsing

**Comment by liuchao173** [comment]
I get it

**Pull request merged**
