### PR TITLE
Adding Travis bagde

### PR DESCRIPTION
**Pull request by szepeviktor**
The title is a question so I am not sure where to add the badge.

### CODE REVIEW

**Comment by nhorman** [comment]
The readme seems fine, though I would also suggest putting it on the home page (from the gh-pages branch)

**Comment by nhorman** [comment]
I'll pull this, and you can open a subsequent request for the gh-pages update

**Comment by szepeviktor** [comment]
@nhorman Could you add repo description here on GitHub? (top of this page)
http://irqbalance.github.io/irqbalance/

**Comment by nhorman** [comment]
@szepeviktor Its already there, see the view on github link

**Comment by szepeviktor** [comment]
I am talking about this:

image

**Pull request merged**
